# Generated by Django 5.1.6 on 2025-09-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("prompt", "Prompt"),
                            ("scheduled", "Scheduled"),
                            ("periodic", "Periodic"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prompt_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Regex pattern for prompt trigger",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, help_text="Time for scheduled trigger", null=True
                    ),
                ),
                (
                    "periodic_interval",
                    models.DurationField(
                        blank=True, help_text="Interval for periodic trigger", null=True
                    ),
                ),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("action_payload", models.JSONField(default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trigger_type", "active"],
                        name="ai_agent_ga_trigger_cb05d6_idx",
                    )
                ],
            },
        ),
    ]
