# Generated by Django 5.1.12 on 2025-09-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agent_gateway", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenttrigger",
            name="action_payload",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
