[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "requirements.txt", 
    "src/**", 
    "railway.toml",
    "Dockerfile",
]

[deploy]
startCommand = "gunicorn genapp.wsgi"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.pre-deploy]
commands = ["python src/manage.py test"]