[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "requirements.txt", 
    "src/**", 
    "railway.toml",
    "Dockerfile",
]

[deploy]
startCommand = "gunicorn genapp.wsgi"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.pre-deploy]
commands = ["python src/manage.py test src/ai_agent_gateway", "python src/manage.py test src/auth", "python src/manage.py test src/genapp", "python src/manage.py test src/checkouts", "python src/manage.py test src/commando", "python src/manage.py test src/customers"]