# Generated by Django 5.1.3 on 2024-12-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "permissions": (
                    ("advanced", "Advanced Perm"),
                    ("pro", "Pro Perm"),
                    ("basic", "Basic Perm"),
                    {"Basic AI Perm", "basic_ai"},
                )
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="groups",
            field=models.ManyToManyField(to="auth.group"),
        ),
    ]
