# Generated by Django 5.1.3 on 2025-01-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0008_subscriptionprice_featured_subscriptionprice_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionprice",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subscriptionprice",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="featured",
            field=models.BooleanField(
                default=True, help_text="Featured on django pricing page"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionprice",
            name="order",
            field=models.IntegerField(
                default=-1, help_text="Ordering on django pricing page"
            ),
        ),
    ]
