# Generated by Django 5.1.3 on 2025-01-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0009_subscriptionprice_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionprice",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
