# Generated by Django 5.1.3 on 2025-01-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0013_alter_subscriptionprice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="features",
            field=models.TextField(
                blank=True, help_text="Pricing seperated by new line", null=True
            ),
        ),
    ]
