# Generated by Django 5.1.3 on 2025-01-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0016_usersubscription_stripe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="user_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
