# Generated by Django 5.1.3 on 2025-02-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0019_usersubscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "ACTIVE"),
                    ("trialing", "TRIALING"),
                    ("incomplete", "INCOMPLETE"),
                    ("incomplete_expired", "INCOMPLETE_EXPIRED"),
                    ("past_due", "PAST_DUE"),
                    ("cancelled", "CANCELLED"),
                    ("unpaid", "UNPAID"),
                    ("paused", "PAUSED"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
