# Generated by Django 5.1.3 on 2025-02-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0019_usersubscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="calncel_at_period_end",
            field=models.BooleanField(default=False),
        ),
    ]
