# Generated by Django 5.1.12 on 2025-09-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0020_usersubscription_cancel_at_period_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="active",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="user_cancelled",
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
