# Generated by Django 5.1.15 on 2025-12-17 23:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0021_remove_usersubscription_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionprice",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="subscriptions.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
