# Generated by Django 5.1.3 on 2025-01-09 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0010_alter_subscriptionprice_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={"ordering": ["order", "featured", "-updated"]},
        ),
    ]
