# Generated by Django 5.1.3 on 2025-01-09 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscriptions",
            "0012_alter_subscription_options_subscription_featured_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={
                "ordering": ["subscription__order", "order", "featured", "-updated"]
            },
        ),
    ]
